### ISSUE TITLE
undefined method `matches?' for :"\n\n":Symbol

### ISSUE THREAD

**Issue by yegor256** [yegor256/factbase#24]
```
Error:
TestQuery#test_complex_parsing:
NoMethodError: undefined method `matches?' for :"\n\n":Symbol
    lib/factbase/term.rb:81:in `block in and'
    lib/factbase/term.rb:80:in `each'
    lib/factbase/term.rb:80:in `and'
    lib/factbase/term.rb:42:in `matches?'
    lib/factbase/query.rb:47:in `block in each'
    lib/factbase/query.rb:45:in `each'
    lib/factbase/query.rb:45:in `each'
    test/factbase/test_query.rb:61:in `each'
    test/factbase/test_query.rb:61:in `to_a'
    test/factbase/test_query.rb:61:in `block in test_complex_parsing'
    test/factbase/test_query.rb:60:in `each'
    test/factbase/test_query.rb:60:in `test_complex_parsing'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.16`
