### ISSUE TITLE
`sort_by': comparison of Array with nil failed

### ISSUE THREAD

**Issue by yegor256** [yegor256/factbase#85]
```
/usr/local/bundle/gems/factbase-0.0.49/lib/factbase/flatten.rb:41:in `sort_by': comparison of Array with nil failed (ArgumentError)
	from /usr/local/bundle/gems/factbase-0.0.49/lib/factbase/flatten.rb:41:in `it'
	from /usr/local/bundle/gems/factbase-0.0.49/lib/factbase/to_yaml.rb:48:in `yaml'
	from /usr/local/bundle/gems/judges-0.8.0/lib/judges/commands/print.rb:62:in `block in run'
	from /usr/local/bundle/gems/judges-0.8.0/lib/judges/elapsed.rb:28:in `elapsed'
	from /usr/local/bundle/gems/judges-0.8.0/lib/judges/commands/print.rb:57:in `run'
	from /usr/local/bundle/gems/judges-0.8.0/bin/judges:121:in `block (2 levels) in <class:App>'
	from /usr/local/bundle/gems/gli-2.21.1/lib/gli/command_support.rb:131:in `execute'
	from /usr/local/bundle/gems/gli-2.21.1/lib/gli/app_support.rb:298:in `block in call_command'
	from /usr/local/bundle/gems/gli-2.21.1/lib/gli/app_support.rb:3[11](https://github.com/zerocracy/judges-action/actions/runs/9692631565/job/26746689557#step:6:12):in `call_command'
	from /usr/local/bundle/gems/gli-2.21.1/lib/gli/app_support.rb:85:in `run'
	from /usr/local/bundle/gems/judges-0.8.0/bin/judges:194:in `<top (required)>'
	from /usr/local/bundle/bin/judges:25:in `load'
	from /usr/local/bundle/bin/judges:25:in `<main>'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.55`
