### ISSUE TITLE
RuntimeError: Can't find '_id' attribute out of 

### ISSUE THREAD

**Issue by yegor256** [yegor256/factbase#86]
```
RuntimeError: Can't find '_id' attribute out of [what, when, version, cycles, added, removed]
	/app/vendor/bundle/ruby/3.2.0/gems/factbase-0.0.54/lib/factbase/fact.rb:84:in `block in <class:Fact>'
	/app/vendor/bundle/ruby/3.2.0/gems/others-0.0.3/lib/others.rb:38:in `instance_exec'
	/app/vendor/bundle/ruby/3.2.0/gems/others-0.0.3/lib/others.rb:38:in `method_missing'
	/app/vendor/bundle/ruby/3.2.0/gems/factbase-0.0.54/lib/factbase/tee.rb:50:in `block in <class:Tee>'
	/app/vendor/bundle/ruby/3.2.0/gems/others-0.0.3/lib/others.rb:38:in `instance_exec'
	/app/vendor/bundle/ruby/3.2.0/gems/others-0.0.3/lib/others.rb:38:in `method_missing'
	/app/vendor/bundle/ruby/3.2.0/gems/factbase-0.0.54/lib/factbase/accum.rb:62:in `block in <class:Accum>'
	/app/vendor/bundle/ruby/3.2.0/gems/others-0.0.3/lib/others.rb:38:in `instance_exec'
	/app/vendor/bundle/ruby/3.2.0/gems/others-0.0.3/lib/others.rb:38:in `method_missing'
	/app/vendor/bundle/ruby/3.2.0/gems/factbase-0.0.54/lib/factbase/rules.rb:93:in `block in <class:Fact>'
	/app/vendor/bundle/ruby/3.2.0/gems/others-0.0.3/lib/others.rb:38:in `instance_exec'
	/app/vendor/bundle/ruby/3.2.0/gems/others-0.0.3/lib/others.rb:38:in `method_missing'
	/app/vendor/bundle/ruby/3.2.0/gems/factbase-0.0.54/lib/factbase/rules.rb:150:in `include?'
	/app/vendor/bundle/ruby/3.2.0/gems/factbase-0.0.54/lib/factbase/rules.rb:76:in `block (2 levels) in txn'
	/app/vendor/bundle/ruby/3.2.0/gems/factbase-0.0.54/lib/factbase/rules.rb:115:in `block in each'
	/app/vendor/bundle/ruby/3.2.0/gems/factbase-0.0.54/lib/factbase/query.rb:69:in `block in each'
	/app/vendor/bundle/ruby/3.2.0/gems/factbase-0.0.54/lib/factbase/query.rb:58:in `each'
	/app/vendor/bundle/ruby/3.2.0/gems/factbase-0.0.54/lib/factbase/query.rb:58:in `each'
	/app/vendor/bundle/ruby/3.2.0/gems/factbase-0.0.54/lib/factbase/looged.rb:131:in `block in each'
	/app/vendor/bundle/ruby/3.2.0/gems/factbase-0.0.54/lib/factbase/looged.rb:176:in `elapsed'
	/app/vendor/bundle/ruby/3.2.0/gems/factbase-0.0.54/lib/factbase/looged.rb:130:in `each'
	/app/vendor/bundle/ruby/3.2.0/gems/factbase-0.0.54/lib/factbase/rules.rb:114:in `each'
	/app/vendor/bundle/ruby/3.2.0/gems/factbase-0.0.54/lib/factbase/looged.rb:131:in `block in each'
	/app/vendor/bundle/ruby/3.2.0/gems/factbase-0.0.54/lib/factbase/looged.rb:176:in `elapsed'
	/app/vendor/bundle/ruby/3.2.0/gems/factbase-0.0.54/lib/factbase/looged.rb:130:in `each'
	/app/vendor/bundle/ruby/3.2.0/gems/factbase-0.0.54/lib/factbase/rules.rb:75:in `block in txn'
	/app/vendor/bundle/ruby/3.2.0/gems/factbase-0.0.54/lib/factbase/looged.rb:64:in `block in txn'
	/app/vendor/bundle/ruby/3.2.0/gems/factbase-0.0.54/lib/factbase.rb:168:in `txn'
	/app/vendor/bundle/ruby/3.2.0/gems/factbase-0.0.54/lib/factbase/looged.rb:62:in `txn'
	/app/vendor/bundle/ruby/3.2.0/gems/factbase-0.0.54/lib/factbase/rules.rb:72:in `txn'
	/app/vendor/bundle/ruby/3.2.0/gems/factbase-0.0.54/lib/factbase/pre.rb:51:in `txn'
	/app/vendor/bundle/ruby/3.2.0/gems/factbase-0.0.54/lib/factbase/looged.rb:62:in `txn'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.56`
